/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void delay(void){
	for(uint32_t i = 0; i <300000; i++){

	}
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t volatile *const pClkCtrlReg = (uint32_t*) (0x40023830); //AHB1ENR
	uint32_t volatile *const pPortDModeReg = (uint32_t*) (0x40020C00);
	uint32_t volatile *const pInputDataReg = (uint32_t*) (0x40020C00+0x10);
	uint32_t volatile *const pOutputDataReg = (uint32_t*) (0x40020C00+0x14);
	uint32_t volatile *const pPullUpDownReg = (uint32_t*) (0x40020C00+0x0C);

	//1. Enable the peripheral clock of GPIOD peripheral
	*pClkCtrlReg |= (1 << 3);

	//2. Configure PD1 2 3 4 output (rows)
	*pPortDModeReg &= ~(0xFF); //reset 0 1 2 3
	*pPortDModeReg |= 0x55;

	//3. Configure PD8 9 10 11 as input
	*pPortDModeReg &= ~(0xFF << 16);

	//4. Enable internal pull-up resistor for PD8 9 10 11
	*pPullUpDownReg &= ~(0xFF << 16);
	*pPullUpDownReg |= (0x55 << 16);

while(1){
	//make all rows HIGH
	*pOutputDataReg |= 0x0f;
	//make R1 LOW(PD0)
	*pOutputDataReg &= ~(1 << 0);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInputDataReg & (1 << 8))){
		delay();
		printf("1\n"); //key is pressed
	}
	//check C2(PD9) low or high
	if(!(*pInputDataReg & (1 << 9))){
		delay();
		printf("2\n"); //key is pressed
	}
	//check C3(PD9) low or high
	if(!(*pInputDataReg & (1 << 10))){
		delay();
		printf("3\n"); //key is pressed
	}
	//check C4(PD10) low or high
	if(!(*pInputDataReg & (1 << 11))){
		delay();
		printf("A\n"); //key is pressed
	}



	//make all rows HIGH
	*pOutputDataReg |= 0x0f;
	//make R2 LOW(PD0)
	*pOutputDataReg &= ~(1 << 1);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInputDataReg & (1 << 8))){
		delay();
		printf("4\n"); //key is pressed
	}
	//check C2(PD9) low or high
	if(!(*pInputDataReg & (1 << 9))){
		delay();
		printf("5\n"); //key is pressed
	}
	//check C3(PD9) low or high
	if(!(*pInputDataReg & (1 << 10))){
		delay();
		printf("6\n"); //key is pressed
	}
	//check C4(PD10) low or high
	if(!(*pInputDataReg & (1 << 11))){
		delay();
		printf("B\n"); //key is pressed
	}



	//make all rows HIGH
	*pOutputDataReg |= 0x0f;
	//make R3 LOW(PD0)
	*pOutputDataReg &= ~(1 << 2);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInputDataReg & (1 << 8))){
		delay();
		printf("7\n"); //key is pressed
	}
	//check C2(PD9) low or high
	if(!(*pInputDataReg & (1 << 9))){
		delay();
		printf("8\n"); //key is pressed
	}
	//check C3(PD9) low or high
	if(!(*pInputDataReg & (1 << 10))){
		delay();
		printf("9\n"); //key is pressed
	}
	//check C4(PD10) low or high
	if(!(*pInputDataReg & (1 << 11))){
		delay();
		printf("C\n"); //key is pressed
	}



	//make all rows HIGH
	*pOutputDataReg |= 0x0f;
	//make R4 LOW(PD0)
	*pOutputDataReg &= ~(1 << 3);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInputDataReg & (1 << 8))){
		delay();
		printf("*\n"); //key is pressed
	}
	//check C2(PD9) low or high
	if(!(*pInputDataReg & (1 << 9))){
		delay();
		printf("0\n"); //key is pressed
	}
	//check C3(PD9) low or high
	if(!(*pInputDataReg & (1 << 10))){
		delay();
		printf("#\n"); //key is pressed
	}
	//check C4(PD10) low or high
	if(!(*pInputDataReg & (1 << 11))){
		delay();
		printf("D\n"); //key is pressed
	}
}
}
